# Generated by Django 5.0.6 on 2024-05-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryStore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('self-improvement', 'Self-improvement'), ('fiction', 'Fiction'), ('romance', 'Romance'), ('scientific', 'Scientific'), ('comedy', 'Comedy'), ('drama', 'Drama')], default='Self-improvement', max_length=50),
        ),
    ]
